=== aritzjl/aritzjl.github.io/XMLyXSD/XSDInfoNoticias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <xs:element name="newsList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="news" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="image" type="xs:string"/>
              <xs:element name="NameFNot" type="xs:string"/>
              <xs:element name="NewsFLit" type="xs:string"/>
              <xs:element name="NameNoticias" type="xs:string"/>
              <xs:element name="NewsLittle" type="xs:string"/>
              <xs:element name="NoticiasTitle" type="xs:string"/>
              <xs:element name="NoticiasFoto" type="xs:string"/>
              <xs:element name="newsText" type="xs:string"/>
              <xs:element name="PrimeroText" type="xs:string"/>
              <xs:element name="SegundoText" type="xs:string"/>
              <xs:element name="TerseroText" type="xs:string"/>
              <xs:element name="CuartoText" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== aritzjl/aritzjl.github.io/XMLyXSD/XMLInfoNoticias.xml
<?xml version="1.0" encoding="UTF-8"?>
<newsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/XMLyXSD/XSDInfoNoticias.xsd">

<news id="noticiaFast1">
    <image>imagenes/noticiaXD2.jpg</image>
    <NameFNot>España no consiente el desquite de Croacia</NameFNot>
    <NewsFLit>La selección masculina vuelve a vencer (10-6) al mismo rival como en la final del Europeo</NewsFLit>
    <NewsFPrimeroT>La anunciada revancha de la final del reciente Europeo masculino de waterpolo entre España y Croacia no terminó en desquite de los balcánicos. Fue más bien la continuación de aquel partido por una sabia decisión del seleccionador David Martín, que asignó la portería a Edu Lorrio, para que los croatas se acordasen de aquel último cuarto de la final en el que el madrileño sustituyó a Unai Aguirre y mantuvo su meta a cero. </NewsFPrimeroT>
    <NewsFSegundoT>Un movimiento técnico y estratégico que dio resultado, porque Lorrio protagonizó otra gran actuación y España ganó mayor notable superioridad (10-6). A la prestación de su guardameta le acompañó una notable defensa de sus compañeros, que dejaron a Croacia en tres goles hasta el último cuarto.</NewsFSegundoT>
    <NewsFTersero>España no regaló ningún balón en juego, ni siquiera en el área croata, como hizo Miguel de Toro en la boya para asistir a Perrone, que abrió el marcador, y Bustos puso el 2-0 en jugada de hombre de más. Lazic respondió antes del primer descanso, pero nada más reanudarse el juego Granados marcó el 3-1 también en superioridad numérica, jugadas en las que España tuvo una eficacia superior al 50%. </NewsFTersero>
    <NewsFCuartoT>Un lanzamiento lejano de Zuvela y otro gol de Loncar en hombre de más forzaron el único empate del partido (3-3), que encontró la respuesta de Munarriz desde el centro y Cabanas esquinado, ambos en superioridad, para llegar al descanso largo con 5-3.</NewsFCuartoT>
</news>
<news id="noticiaFast2">
    <image>imagenes/noticiaXD2.jpg</image>
    <NameFNot>España arrasa a Grecia y mete la directa hacia cuartos</NameFNot>
    <NewsFLit>Como en el reciente Europeo, la selección de Miki Oca supera con autoridad a las helenas (16-8)</NewsFLit>
    <NewsFPrimeroT>Como ocurrió en las semifinales del Europeo de Eindhoven, cuando derrotó a Grecia por 13-5, España volvió a repetir victoria para asegurarse la clasificación directa a cuartos de final al pasar por encima de las helenas con mucha solvencia (16-8).</NewsFPrimeroT>
    <NewsFSegundoT>El partido era el más importante de la fase de clasificación, frente a una selección que está clasificada para los Juegos Olímpicos de París y España estuvo espléndida. Con una defensa superior, un ataque con multitud de opciones y grandes sensaciones, el equipo de Miki Oca destila grandes sensaciones.</NewsFSegundoT>
    <NewsFTersero>Y eso que de salida no tuvo continuidad en ataque. Entre las intervenciones de la meta Stamatopoulou y la mala selección de chut, España no se sentía a gusto. Además, la diferencia el número de exclusiones en el primer cuarto (4-2) permitió las primeras diferencias de las helenas, que se adelantaron dos veces en el marcador (0-1 y 1-2).</NewsFTersero>
    <NewsFCuartoT>Sin embargo, un tanto de Bea Ortiz y otro, a dos segundos del final de los primeros ocho minutos,de Anna Espar, equilibraron la balanza (2-2). A partir de entonces, el partido tomó otro rumbo. El parcial aumentó en el inicio del segundo, donde brilló especialmente Paula Leitón, forzando un penalti y anotando un tanto en superioridad.</NewsFCuartoT>
</news>
<news id="noticiaFast3">
    <image>imagenes/noticiaXD2.jpg</image>
    <NameFNot>España arranca con goleada el Mundial masculino de waterpolo</NameFNot>
    <NewsFLit>Se impone a Sudáfrica por un contundente 21-5</NewsFLit>
    <NewsFPrimeroT>España, actual campeona de Europa, pasó por encima de Sudáfrica, a la que apabulló por 5-21 en su primer partido en el Mundial de waterpolo. El equipo de David Martín tuvo un plácido estreno. Los campeones de Europa repartieron minutos de juego y apenas pudieron probar sistemas de juego ante uno de los rivales de menor entidad del concierto mundial.</NewsFPrimeroT>
    <NewsFSegundoT>Tardó 52 segundos Álvaro Granados, el héroe de Zagreb, en anotar su primer tanto y España encadenó un parcial 0-5, cortado con un penalti anotado por Swanepoel. Al término del primer cuarto, ya estaba todo decidido (1-6).</NewsFSegundoT>
    <NewsFTersero>Sin Alberto Munárriz y Roger Tahull, que fueron los descartes; la apuesta a partir de entonces fue un ejercicio defensivo. Se quedó a cero el marco de Edu Lorrio en el segundo parcial. El meta del Sabadell había parado siete de los ocho lanzamientos realizados por los sudafricanos, solo encajó de penalti; el sudafricano Lwazi Madi encajó los trece remates recibidos.</NewsFTersero>
    <NewsFCuartoT></NewsFCuartoT>
</news>


<news id="noticia1">
    <NameNoticias>Opciones de medalla españolas en los Mundiales de natación, waterpolo y artística de Doha 2024</NameNoticias>
    <NewsLittle>La 'sincro' y el waterpolo, las opciones más realistas y probables</NewsLittle>

    <NoticiasTitle>España - Croacia: a qué hora es, dónde ver en TV y canal de la final del Europeo de waterpolo 2024</NoticiasTitle>
    <NoticiasFoto>imagenes/noticiasNormal.png</NoticiasFoto>
    <newsText>Nuevo Texto de la Noticia</newsText>
    <PrimeroText>La selpara los Juegos Olímpicos de París.</PrimeroText>
    <SegundoText>a representación española sumó nueve medallas en los Campeonatos del Mundo de natación, waterpolo, artística y saltos de 2023. Se las repartieron siete la 'sincro' y dos las selecciones de waterpolo. En los Mundiales que comienzan este viernes en Doha (Qatar) podrían alcanzarse un número parecido, aunque lo realmente importante son las plazas olímpicas que se sumen a las que ya poseen los equipos de waterpolo (2), Hugo González (natación) y Ana Carvajal (saltos).</SegundoText>
    <TerseroText>Luego España ganó a Montenegro y Francia para acabar primera de grupo al perder Croacia con Montenegro en los penaltis. En cuartos se impuso a Rumania (24-7) y en semifinales a Italia por 7-4 con una gran actuación del meta Unai Aguirre.</TerseroText>
    <CuartoText>El combinado nacional llega a la final tras sumar una única derrota, precisamente ante Croacia en el primer partido. Cayó en los penaltis en un encuentro en el que le pasó factura la acumulación de exclusiones: 19, seis más que a los croatas, que marcaron siete de sus nueve goles en juego con un hombre de más.</CuartoText>
</news>
<news id="noticia2">
    <NameNoticias>Noticia2</NameNoticias>
    <NewsLittle>Вот самые х пор, в обратном хyi ронологическом порядке</NewsLittle>

    <NoticiasTitle>dgfnbd gb fghdn b dónde ver en TV y canal de la final del Europeo de waterpolo 2024</NoticiasTitle>
    <NoticiasFoto>imagenes/noticiasNormal.png</NoticiasFoto>
    <newsText>Nuevo Texto de la Noticia</newsText>
    <PrimeroText>La selección masculina persigue el único título que se le resiste. Una victoria también le daría el billete para los Juegos Olímpicos de París.</PrimeroText>
    <SegundoText>La selección masculina de waterpolo busca el único título que le falta en su palmarés: el campeonato de Europa. Con un oro olímpico (Atlanta 96) y tres mundiales (1998, 2001, 2022), se le resiste ceñirse la corona continental. En tres ocasiones se quedó a las puertas al caer en la final (1991, 2018 y 2020). Ahora tiene una nueva oportunidad. España se medirá a Croacia, en Zagreb, en el último partido del Europeo, este martes 16 de enero a partir de las 20.15 horas. En juego, el oro y la clasificación para los Juegos de París.</SegundoText>
    <TerseroText>Luego España ganó a Montenegro y Francia para acabar primera de grupo al perder Croacia con Montenegro en los penaltis. En cuartos se impuso a Rumania (24-7) y en semifinales a Italia por 7-4 con una gran actuación del meta Unai Aguirre.</TerseroText>
    <CuartoText>El combinado nacional llega a la final tras sumar una única derrota, precisamente ante Croacia en el primer partido. Cayó en los penaltis en un encuentro en el que le pasó factura la acumulación de exclusiones: 19, seis más que a los croatas, que marcaron siete de sus nueve goles en juego con un hombre de más.</CuartoText>
</news>
<news id="noticia3">
    <NameNoticias>Noticia3</NameNoticias>
    <NewsLittle>Вdsfgdvsdfgот самые крупные предприятельские технологические сделки 2021 года до сих пор, в обратном хронологическом порядке</NewsLittle>

    <NoticiasTitle>13434556654767980ver en TV y canal de la final del Europeo de waterpolo 2024</NoticiasTitle>
    <NoticiasFoto>imagenes/noticiasNormal.png</NoticiasFoto>
    <newsText>Nuevo Texto de la Noticia</newsText>
    <PrimeroText>La selección masculina persigue el único título que se le resiste. Una victoria también le daría el billete para los Juegos Olímpicos de París.</PrimeroText>
    <SegundoText>La selección masculina de waterpolo busca el único título que le falta en su palmarés: el campeonato de Europa. Con un oro olímpico (Atlanta 96) y tres mundiales (1998, 2001, 2022), se le resiste ceñirse la corona continental. En tres ocasiones se quedó a las puertas al caer en la final (1991, 2018 y 2020). Ahora tiene una nueva oportunidad. España se medirá a Croacia, en Zagreb, en el último partido del Europeo, este martes 16 de enero a partir de las 20.15 horas. En juego, el oro y la clasificación para los Juegos de París.</SegundoText>
    <TerseroText>Luego España ganó a Montenegro y Francia para acabar primera de grupo al perder Croacia con Montenegro en los penaltis. En cuartos se impuso a Rumania (24-7) y en semifinales a Italia por 7-4 con una gran actuación del meta Unai Aguirre.</TerseroText>
