=== aritzjl/aritzjl.github.io/XMLyXSD/XSDPersonas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com"
           xmlns="http://example.com"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:element name="Personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="equipo1" type="TeamType"/>
        <xs:element name="equipo2" type="TeamType"/>
        <xs:element name="equipo3" type="TeamType"/>
        <xs:element name="equipo4" type="TeamType"/>
        <xs:element name="equipo5" type="TeamType"/>
        <xs:element name="equipo6" type="TeamType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TeamType">
    <xs:sequence>
      <xs:element name="jugador1" type="PlayerType"/>
      <xs:element name="jugador2" type="PlayerType"/>
      <xs:element name="jugador3" type="PlayerType"/>
      <xs:element name="jugador4" type="PlayerType"/>
      <xs:element name="jugador5" type="PlayerType"/>
      <xs:element name="jugador6" type="PlayerType"/>
      <xs:element name="jugador7" type="PlayerType"/>
      <xs:element name="jugador8" type="PlayerType"/>
      <xs:element name="jugador9" type="PlayerType"/>
      <xs:element name="jugador10" type="PlayerType"/>
      <xs:element name="jugador11" type="PlayerType"/>
      <xs:element name="jugador12" type="PlayerType"/>
      <xs:element name="jugador13" type="PlayerType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PlayerType">
    <xs:sequence>
      <xs:element name="Fotca" type="xs:string"/>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Anos" type="xs:string"/>
      <xs:element name="Alt" type="xs:string"/>
      <xs:element name="Peso" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== aritzjl/aritzjl.github.io/XMLyXSD/XMLPersonas.xml
<?xml version="1.0" encoding="UTF-8"?>
<Personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/XMLyXSD/XSDPersonas.xsd">
    <club1>
        <jugador1>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador1>
        <jugador2>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador2>
        <jugador3>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador3>
        <jugador4>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador4>
        <jugador5>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador5>
        <jugador6>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador6>
        <jugador7>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador7>
        <jugador8>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador8>
        <jugador9>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador9>
        <jugador10>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador10>
        <jugador11>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador11>
        <jugador12>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador12>
        <jugador13>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>Tailer Derden</Name>
            <Anos>31</Anos>
            <Alt>173</Alt>
            <Peso>81</Peso>
        </jugador13>
    </club1>

    <club2>
        <jugador1>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador1>
        <jugador2>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador2>
        <jugador3>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador3>
        <jugador4>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador4>
        <jugador5>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador5>
        <jugador6>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador6>
        <jugador7>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador7>
        <jugador8>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador8>
        <jugador9>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador9>
        <jugador10>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador10>
        <jugador11>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador11>
        <jugador12>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador12>
        <jugador13>
            <Fotca>/imagenes/img2.png</Fotca>
            <Name>daun</Name>
            <Anos>34567</Anos>
            <Alt>234</Alt>
            <Peso>6790</Peso>
        </jugador13>
    </club2>

    <club3>
        <jugador1>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador1>
        <jugador2>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador2>
        <jugador3>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador3>
        <jugador4>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador4>
        <jugador5>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador5>
        <jugador6>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador6>
        <jugador7>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador7>
        <jugador8>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador8>
        <jugador9>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador9>
        <jugador10>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador10>
        <jugador11>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador11>
        <jugador12>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador12>
        <jugador13>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador13>
    </club3>

    <equipo4>
        <jugador1>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador1>
        <jugador2>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador2>
        <jugador3>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador3>
        <jugador4>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador4>
        <jugador5>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador5>
        <jugador6>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador6>
        <jugador7>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador7>
        <jugador8>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador8>
        <jugador9>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador9>
        <jugador10>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador10>
        <jugador11>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador11>
        <jugador12>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
        </jugador12>
        <jugador13>
            <Fotca></Fotca>
            <Name></Name>
            <Anos></Anos>
            <Alt></Alt>
            <Peso></Peso>
