=== aritzjl/aritzjl.github.io/XSDClasificacion.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="teams">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="team" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="position" type="xs:integer"/>
              <xs:element name="escudo_path" type="xs:string"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="ganados" type="xs:integer"/>
              <xs:element name="perdidos" type="xs:integer"/>
              <xs:element name="empatados" type="xs:integer"/>
              <xs:element name="jugados" type="xs:integer"/>
              <xs:element name="goles_f" type="xs:integer"/>
              <xs:element name="goles_c" type="xs:integer"/>
              <xs:element name="puntos" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== aritzjl/aritzjl.github.io/XMLyXSD/XMLClasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/XMLyXSD/XSDClasificacion.xsd">
<temporada id="2022">
    <team>
        <position>1</position>
        <escudo_path>/imagenes/Spirit.png</escudo_path>
        <nombre>Team Spirit</nombre>
        <ganados>9</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>5</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>23</puntos>
    </team>
    <team>
        <position>2</position>
        <escudo_path>/imagenes/gladiators.png</escudo_path>
        <nombre>Gladiators</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>24</goles_f>
        <goles_c>16</goles_c>
        <puntos>14</puntos>
    </team>
    <!-- Добавленная строка -->
    <team>
        <position>3</position>
        <escudo_path>/imagenes/logoEquipo2.jpg</escudo_path>
        <nombre>Fight Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>10</jugados>
        <goles_f>30</goles_f>
        <goles_c>10</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>4</position>
        <escudo_path>/imagenes/logoEquipo.png</escudo_path>
        <nombre>WaterPolo Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>25</goles_f>
        <goles_c>15</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>5</position>
        <escudo_path>/imagenes/Virtus.png</escudo_path>
        <nombre>Virtus.pro</nombre>
        <ganados>7</ganados>
        <perdidos>3</perdidos>
        <empatados>1</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>6</position>
        <escudo_path>/imagenes/Navi.png</escudo_path>
        <nombre>Navi</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>7</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>1</position>
        <escudo_path>/imagenes/Spirit.png</escudo_path>
        <nombre>Team Spirit</nombre>
        <ganados>9</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>5</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>23</puntos>
    </team>
    <team>
        <position>2</position>
        <escudo_path>/imagenes/gladiators.png</escudo_path>
        <nombre>Gladiators</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>24</goles_f>
        <goles_c>16</goles_c>
        <puntos>14</puntos>
    </team>
    <!-- Добавленная строка -->
    <team>
        <position>3</position>
        <escudo_path>/imagenes/logoEquipo2.jpg</escudo_path>
        <nombre>Fight Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>10</jugados>
        <goles_f>30</goles_f>
        <goles_c>10</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>4</position>
        <escudo_path>/imagenes/logoEquipo.png</escudo_path>
        <nombre>WaterPolo Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>25</goles_f>
        <goles_c>15</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>5</position>
        <escudo_path>/imagenes/Virtus.png</escudo_path>
        <nombre>Virtus.pro</nombre>
        <ganados>7</ganados>
        <perdidos>3</perdidos>
        <empatados>1</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>6</position>
        <escudo_path>/imagenes/Navi.png</escudo_path>
        <nombre>Navi</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>7</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
</temporada>
<temporada id="2023">
    <team>
        <position>1</position>
        <escudo_path>/imagenes/Spirit.png</escudo_path>
        <nombre>Team Spirit</nombre>
        <ganados>9</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>5</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>23</puntos>
    </team>
    <team>
        <position>2</position>
        <escudo_path>/imagenes/gladiators.png</escudo_path>
        <nombre>Gladiators</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>24</goles_f>
        <goles_c>16</goles_c>
        <puntos>14</puntos>
    </team>
    <!-- Добавленная строка -->
    <team>
        <position>3</position>
        <escudo_path>/imagenes/logoEquipo2.jpg</escudo_path>
        <nombre>Fight Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>10</jugados>
        <goles_f>30</goles_f>
        <goles_c>10</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>5</position>
        <escudo_path>/imagenes/Virtus.png</escudo_path>
        <nombre>Virtus.pro</nombre>
        <ganados>7</ganados>
        <perdidos>3</perdidos>
        <empatados>1</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>6</position>
        <escudo_path>/imagenes/Navi.png</escudo_path>
        <nombre>Navi</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>7</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
</temporada>
<temporada id="2024">
    <team>
        <position>1</position>
        <escudo_path>/imagenes/Spirit.png</escudo_path>
        <nombre>Team Spirit</nombre>
        <ganados>9</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>5</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>23</puntos>
    </team>
    <team>
        <position>2</position>
        <escudo_path>/imagenes/gladiators.png</escudo_path>
        <nombre>Gladiators</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>24</goles_f>
        <goles_c>16</goles_c>
        <puntos>14</puntos>
    </team>
    <!-- Добавленная строка -->
    <team>
        <position>3</position>
        <escudo_path>/imagenes/logoEquipo2.jpg</escudo_path>
        <nombre>Fight Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>10</jugados>
        <goles_f>30</goles_f>
        <goles_c>10</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>4</position>
        <escudo_path>/imagenes/logoEquipo.png</escudo_path>
        <nombre>WaterPolo Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>25</goles_f>
        <goles_c>15</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>5</position>
        <escudo_path>/imagenes/Virtus.png</escudo_path>
        <nombre>Virtus.pro</nombre>
        <ganados>7</ganados>
        <perdidos>3</perdidos>
        <empatados>1</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>6</position>
        <escudo_path>/imagenes/Navi.png</escudo_path>
        <nombre>Navi</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>7</empatados>
        <jugados>10</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>17</puntos>
    </team>
</temporada>
<temporada id="2025">
    <team>
        <position>1</position>
        <escudo_path>/imagenes/Spirit.png</escudo_path>
        <nombre>Team Spirit</nombre>
        <ganados>9</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>5</jugados>
        <goles_f>28</goles_f>
        <goles_c>12</goles_c>
        <puntos>23</puntos>
    </team>
    <team>
        <position>2</position>
        <escudo_path>/imagenes/gladiators.png</escudo_path>
        <nombre>Gladiators</nombre>
        <ganados>7</ganados>
        <perdidos>2</perdidos>
        <empatados>5</empatados>
        <jugados>10</jugados>
        <goles_f>24</goles_f>
        <goles_c>16</goles_c>
        <puntos>14</puntos>
    </team>
    <!-- Добавленная строка -->
    <team>
        <position>3</position>
        <escudo_path>/imagenes/logoEquipo2.jpg</escudo_path>
        <nombre>Fight Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
        <empatados>2</empatados>
        <jugados>10</jugados>
        <goles_f>30</goles_f>
        <goles_c>10</goles_c>
        <puntos>17</puntos>
    </team>
    <team>
        <position>4</position>
        <escudo_path>/imagenes/logoEquipo.png</escudo_path>
        <nombre>WaterPolo Club</nombre>
        <ganados>7</ganados>
        <perdidos>1</perdidos>
